### PR TITLE
Supporting unordered lists in docblocks

### PR DESCRIPTION
**Pull request by hashchange**
I have added support for unordered lists in docblocks. Plain text lists beginning with -, +, # or o are recognized and turned into &lt;ul&gt;s. I have tried to make it a little restrictive and only capture stuff that definitely is a list - have a look at the testcase.

And that's it for today ;-)

Cheers,

Michael

### CODE REVIEW

**Comment by peej** [comment]
Hi Michael,

My problems with this is that it mixes HTML into the parser, binding the output to be able to render that HTML even if the doclet used is for another format. It also seems like it'd be a good idea to allow pluggable format processors, so that people can do things like use markdown or textile if they so wish.

Any thoughts?

**Comment by hashchange** [comment]
Hi Paul,

I agree - it just was the easiest way to do it because later on the formatting information is gone.

Anyway, now I have turned it into a formatter that can be exchanged or extended easily. The formatter is injected into the tags so it can modify text right there.

**Comment by peej** [comment]
Great work.

Wouldn't it be easier to simply bolt the formatter into the doclet and keep in out of the parsing phase? Or did you run into trouble with that approach?

**Comment by hashchange** [comment]
I had thought about that but actually found this solution cleaner. The formatter doesn't interact with the parser. It's just the taglet factory which needs it - and the factory happens to be implemented as a method of the parser, true, but that's where the relationship ends.

Why there and not in the doclet? The formatting information is stored in the taglet. On the other hand, the formatter is independent of a specific doclet. Their output type (HTML) must match, but apart from that, I thought the doclet shouldn't have to know how the formatting is handled or even that it exists. That way the doclet just asks the taglet for its contents, and the taglet takes care of itself.

(Actually, there are still some bits of HTML in the taglets themselves, e.g. for the link in the see tag, which could easily be shoved into a formatter method to keep the markup separate. That kind of thing would be more difficult if the formatter was called from the doclet.)

**Comment by peej** [comment]
Hi Michael,

You are of course right.

I've been having problems getting the parser tests to run across your changes. Something somewhere seems to be making the execution halt mid-flow. Have you had any problems with it?

**Comment by hashchange** [comment]
Actually no, the tests are all passing. I've checked with PHP 5.3.2/Ubuntu Lucid and with PHP 5.2.9/Windows 7 (using cli, I haven't tried the web interface).

**Comment by hashchange** [comment]
Oops - actually yes, I seem to have overlooked that the parser tests were commented out. I'll look into this.

**Comment by hashchange** [comment]
The parser test pass now, too - the debug doclet hadn't been adjusted. And the test suite now works fully for Windows and PHP < 5.3, no need to comment out anything ;-)

**Comment by peej** [comment]
Nice one Michael. I've pulled this request, thanks for all your hard work.

**Pull request merged**
